### ISSUE TITLE
How can I merge two styles?

### ISSUE THREAD

**Issue by akiradeveloper** [scalajs-react-interface/sri#13]
In the old sri project, there was a `styleE` to merge two styles but I couldn't find any in this project. How can I merge two styles?

**Comment by chandu0101** [comment]
now `style` returns id for all the style attributes . if you want to merge two styles just put them in array while accessing  

```scala
View(style = js.Array(styles.style1,styles.style2))()
```

**Comment by akiradeveloper** [comment]
Thanks
