### ISSUE TITLE
IDEA missing implicit conversion demo

### ISSUE THREAD

**Issue by chandu0101** [scalajs-react-interface/sri#2]
https://github.com/cuzfrog/web-examples/tree/master/sample#idea-missing-implicit-conversion-demo

**Comment by chandu0101** [comment]
@cuzfrog 

thanks for the detailed report. 

1) could you please elaborate more on this line `def div()(pl:Long)(implicit: tool:Tool) ` what exactly `Tool` trait is going to implement.. 

2) so with new approach if we want to pass just children to div tag then we should use `
div()(1L)` at call site ? if yes why we need overloaded method!.

**Comment by cuzfrog** [comment]
Thanks for you attention.

Alignment of parameter group of overloaded method should be generally adapted. Not specific to this html `div`. I carry some special care towards method overloading from the java world.

#### for 1:
Say, with html dom, in particular, `div`. Implicit parameter example could be like this:
```scala
def div(key:String)(children:Node*)(implicit tool:ValidationTool) = {
  tool.validateKey(key).foreach(logger.warn)
  //etc...
}

trait Tool
object ValidationTool extends Tool{
  /** Return warning msg if validation failed. */
  def validateKey(key:String):Option[String] = if(key.length>20) Some("Key is too long.") else None
}
```

#### for 2: (yes)

As long as methods' name are the same, either
 `div(ps:String)(p:Int)` with `div(p:Int)`  
or 
 `div(ps:String)(p:Int)` with `div()(p:Int)`  
is method overloading. We probably cannot avoid overloading for some other better reason. But we may use overloading more properly. Using `div()(p:Int)` has no compatibility problem with IDEA while does not have the problem I demonstrated.

If my thought contains any flaw, teach me.

edit: Yes. the second method is to be redundant. The method with all default values substantially overlaps the other.

**Comment by chandu0101** [comment]
>for 2: (yes)

then we don't need `overloaded method`

```scala
@inline
  def bad[T <: dom.Node](style: U[js.Any] = NoValue,
                          id: U[String] = NoValue,
                          className: U[String] = NoValue,
                          @exclude key: String | Int = null,
                          @exclude ref: js.Function1[T, Unit] = null,
                          @exclude extraProps: U[DOMProps] = NoValue)(
                           children: ReactNode*): ReactElement = ???

//call site 
 bad(
      key = "key1",
      className = "class1 class2"
    )("Child1", "Child2")
or 
bad()(1L)
```
