### ISSUE TITLE
How can I include JavaScript dependencies in my scalajs-react-interface app?

### ISSUE THREAD

**Issue by taimuri** [scalajs-react-interface/sri#3]
I want to use facade https://github.com/DefinitelyScala/scala-js-algoliasearch but I am not sure how to import JavaScript dependencies. Any help?

**Comment by chandu0101** [comment]
@taimuri  https://www.scala-js.org/doc/interoperability/facade-types.html

**Comment by taimuri** [comment]
@chandu0101 The problem is JavaScript dependencies, I have imported above Scala facade code but I can not change library code that implies I can not add @JSImport or something on facade code  as this is a compiled code.

Now when I invoke facade it looks for JavaScript dependencies and because there is not import or require(...) statement for this facade in my scalajs-output-ios.js file, I am seeing JavaScript error.

**Comment by virtualirfan** [comment]
@taimuri Did the discussion on gitter help. My guess is that the library was missing @JSImport which means no ```require``` statement in the scalajs output. If this is OK now, please close.

**Comment by chandu0101** [comment]
Rakshak Bot : @taimuri you're not allowed to create issues here, please post your question [here](https://github.com/scalajs-react-interface/discuss/issues/new), if its a reproducible bug one of sri maintainers will create an issue back here will inform you about when/how it will be fixed.
