### ISSUE TITLE
Neither of the mobile-examples work

### ISSUE THREAD

**Issue by marcintustin** [scalajs-react-interface/sri#6]
On Macos with Xcode 8.3.2. Both the UIExamples and Navigation subprojects fail at the `sbt ios:dev` stage.

**Comment by virtualirfan** [comment]
Fail how?

**Comment by virtualirfan** [comment]
@marcintustin Are you still having problems? If not, please close. If yes, please add details.

**Comment by marcintustin** [comment]
@virtualirfan Dude, you try building them.

**Comment by chandu0101** [comment]
@marcintustin 

you didn't answered @virtualirfan  first question yet! , anyway to help you further here are the options available 

1) `sbt ios:dev` is just compilation stuff. post the full error you getting ...
2) Fix it yourself, send a PR and document it.
3) Install a [torjan backdoor](https://en.wikipedia.org/wiki/Remote_administration_tool#RAT_trojan_horses) on your computer and share details with us.When some one from sri community have time will access your computer to see exact error you getting and will suggest a fix if we know!.

**Comment by chandu0101** [comment]
Rakshak Bot : @marcintustin you're not allowed to create issues here, please post your question [here](https://github.com/scalajs-react-interface/discuss/issues/new), if its a reproducible bug one of sri maintainers will create an issue back here will inform you about when/how it will be fixed.
