### ISSUE TITLE
Add fields to the ConcreteBatch facade in relay

### ISSUE THREAD

**Issue by virtualirfan** [scalajs-react-interface/sri#7]
It appears that in JS, ConcreteBatch has these fields. In particular, I needed to reference ```.text```.

```
/*: ConcreteBatch*/
{
  "fragment": {…},
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "appQuery",
  "query": {…},
  "text": {…},
};

**Comment by chandu0101** [comment]
Rakshak Bot : @virtualirfan you're not allowed to create issues here, please post your question [here](https://github.com/scalajs-react-interface/discuss/issues/new), if its a reproducible bug one of sri maintainers will create an issue back here will inform you about when/how it will be fixed.
